@URL=http://localhost:5286

GET {{URL}}/weatherforecast/
Accept: application/json

###

GET {{URL}}/api/books
Accept: application/json

###
GET {{URL}}/api/books/2
Accept: application/json
###
POST {{URL}}/api/books
Accept: application/json

###
PUT {{URL}}/api/books/2
Accept: application/json

###
DELETE {{URL}}/api/books/6
