//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string TACGIA { get; set; }
        public string NAMXB { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string IMAGECOVER { get; set; }
    }
}
