name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies BookAPI
      run: dotnet restore BookAPI/FirstAPI/FirstAPI.csproj
    - name: Build BookAPI
      run: dotnet build BookAPI/FirstAPI/FirstAPI.csproj --no-restore
    - name: Test BookAPI
      run: dotnet test BookAPI/FirstAPI/FirstAPI.csproj --no-build --verbosity normal
    - name: Restore dependencies TodoAPI
      run: dotnet restore TodoAPI/backend/backend/backend.csproj
    - name: Build TodoAPI
      run: dotnet build TodoAPI/backend/backend/backend.csproj --no-restore
    - name: Test TodoAPI
      run: dotnet test TodoAPI/backend/backend/backend.csproj --no-build --verbosity normal